# Fairness

> _Lorem ipsum bla bla bla_

In [1]:
# import sys
# sys.path.insert(1, "../")  

import numpy as np
np.random.seed(0)

from aif360.datasets import GermanDataset
from aif360.metrics import BinaryLabelDatasetMetric
from aif360.algorithms.preprocessing import Reweighing

from IPython.display import Markdown, display

In [2]:
dataset_orig = GermanDataset(
    protected_attribute_names=['age'],           # this dataset also contains protected
                                                 # attribute for "sex" which we do not
                                                 # consider in this evaluation
    privileged_classes=[lambda x: x >= 25],      # age >=25 is considered privileged
    features_to_drop=['personal_status', 'sex'] # ignore sex-related attributes
)

dataset_orig_train, dataset_orig_test = dataset_orig.split([0.7], shuffle=True)

privileged_groups = [{'age': 1}]
unprivileged_groups = [{'age': 0}]

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

IOError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/aif360/datasets/../data/raw/german/german.data'
To use this class, please download the following files:

	https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data
	https://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.doc

and place them, as-is, in the folder:

	/opt/conda/lib/python3.7/site-packages/aif360/data/raw/german

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/aif360/datasets/german_dataset.py", line 79, in __init__
    na_values=na_values)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 936, in __init__
    self._make_engine(self.engine)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1168, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1998, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 361, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 653, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/aif360/datasets/../data/raw/german/german.data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-85f96164a29c>", line 6, in <module>
    features_to_drop=['personal_status', 'sex'] # ignore sex-related attributes
  File "/opt/conda/lib/python3.7/site-packages/aif360/datasets/german_dataset.py", line 89, in __init__
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1148, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/opt/conda/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'

SystemExit: 1

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [8]:
metric_orig_train = BinaryLabelDatasetMetric(dataset_orig_train, 
                                             unprivileged_groups=unprivileged_groups,
                                             privileged_groups=privileged_groups)
display(Markdown("#### Original training dataset"))
print("Difference in mean outcomes between unprivileged and privileged groups = %f" % metric_orig_train.mean_difference())

#### Original training dataset

Difference in mean outcomes between unprivileged and privileged groups = -0.169905

In [24]:
metric_orig_train.smoothed_empirical_differential_fairness()

0.48420789321537516

In [18]:
dataset_orig_test.convert_to_dataframe()[0]

,month,credit_amount,investment_as_income_percentage,residence_since,age,number_of_credits,people_liable_for,status=A11,status=A12,status=A13,...,housing=A153,skill_level=A171,skill_level=A172,skill_level=A173,skill_level=A174,telephone=A191,telephone=A192,foreign_worker=A201,foreign_worker=A202,credit
289,24.0,1024.0,4.0,4.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,2.0
29,60.0,6836.0,3.0,4.0,1.0,2.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,2.0
114,12.0,1680.0,3.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
508,24.0,1413.0,4.0,2.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
810,8.0,907.0,3.0,2.0,1.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
835,12.0,1082.0,4.0,4.0,1.0,2.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,2.0
192,27.0,3915.0,4.0,2.0,1.0,1.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,2.0
629,9.0,3832.0,1.0,4.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
559,18.0,1928.0,2.0,2.0,1.0,2.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0
684,36.0,9857.0,1.0,3.0,1.0,2.0,2.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0

In [26]:
type(dataset_orig)

aif360.datasets.german_dataset.GermanDataset

In [27]:
from aif360.datasets import Dataset

In [30]:
dir(Dataset)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 'copy',
 'export_dataset',
 'split',
 'validate_dataset']

Dataset(dataset_orig_test.convert_to_dataframe()[0])

In [19]:
RW = Reweighing(unprivileged_groups=unprivileged_groups,
                privileged_groups=privileged_groups)
dataset_transf_train = RW.fit_transform(dataset_orig_train)

In [20]:
metric_transf_train = BinaryLabelDatasetMetric(dataset_transf_train, 
                                               unprivileged_groups=unprivileged_groups,
                                               privileged_groups=privileged_groups)
display(Markdown("#### Transformed training dataset"))
print("Difference in mean outcomes between unprivileged and privileged groups = %f" % metric_transf_train.mean_difference())

#### Transformed training dataset

Difference in mean outcomes between unprivileged and privileged groups = 0.000000

In [1]:
import sys
sys.path.insert(0, '../')

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Markdown, display

# Datasets
from aif360.datasets import MEPSDataset19
from aif360.datasets import MEPSDataset20
from aif360.datasets import MEPSDataset21

# Fairness metrics
from aif360.metrics import BinaryLabelDatasetMetric
from aif360.metrics import ClassificationMetric

# Explainers
from aif360.explainers import MetricTextExplainer

# Scalers
from sklearn.preprocessing import StandardScaler

# Classifiers
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

# Bias mitigation techniques
from aif360.algorithms.preprocessing import Reweighing
from aif360.algorithms.inprocessing import PrejudiceRemover

# LIME
from aif360.datasets.lime_encoder import LimeEncoder
import lime
from lime.lime_tabular import LimeTabularExplainer

np.random.seed(1)

WARNING:root:No module named 'numba.decorators': LFR will be unavailable. To install, run:
pip install 'aif360[LFR]'

In [2]:
(dataset_orig_panel19_train,
 dataset_orig_panel19_val,
 dataset_orig_panel19_test) = MEPSDataset19().split([0.5, 0.8], shuffle=True)

sens_ind = 0
sens_attr = dataset_orig_panel19_train.protected_attribute_names[sens_ind]

unprivileged_groups = [{sens_attr: v} for v in
                       dataset_orig_panel19_train.unprivileged_protected_attributes[sens_ind]]
privileged_groups = [{sens_attr: v} for v in
                     dataset_orig_panel19_train.privileged_protected_attributes[sens_ind]]

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

IOError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/aif360/datasets/../data/raw/meps/h181.csv'
To use this class, please follow the instructions in:

	/opt/conda/lib/python3.7/site-packages/aif360/data/raw/meps/README.md


 to download and convert the 2015 data and place the final h181.csv file, as-is, in the folder:

	/opt/conda/lib/python3.7/site-packages/aif360/data/raw/meps

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/aif360/datasets/meps_dataset_panel19_fy2015.py", line 94, in __init__
    df = pd.read_csv(filepath, sep=',', na_values=na_values)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 936, in __init__
    self._make_engine(self.engine)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1168, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1998, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/aif360/datasets/../data/raw/meps/h181.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-17d239802529>", line 3, in <module>
    dataset_orig_panel19_test) = MEPSDataset19().split([0.5, 0.8], shuffle=True)
  File "/opt/conda/lib/python3.7/site-packages/aif360/datasets/meps_dataset_panel19_fy2015.py", line 104, in __init__
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1148, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/opt/conda/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'

SystemExit: 1

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [3]:
!cat /opt/conda/lib/python3.7/site-packages/aif360/data/raw/meps/README.md

            * Edit this file to change the FILE HANDLE name to the complete path/name of the downloaded data file, execute the SPSS programming statements to load the data, and 'save as' a comma-delimited file called 'h192.csv' in this folder.

In [3]:
import pandas as pd

In [4]:
pd.read_csv("data/MEPS/h181.csv")

,DUID,PID,DUPERSID,PANEL,FAMID31,FAMID42,FAMID53,FAMID15,FAMIDYR,CPSFAMID,...,RXOSR15,RXPTR15,RXOTH15,PERWT15F,FAMWT15F,FAMWT15C,SAQWT15F,DIABW15F,VARSTR,VARPSU
0,60001,101,60001101,19,A,A,A,A,A,A,...,0,0,0,21854.981705,22983.493815,22983.493815,23226.272970,26185.048789,1019,1
1,60001,102,60001102,19,A,A,A,A,A,B,...,0,0,4,18169.604822,22983.493815,14663.337957,20624.450027,22682.689497,1019,1
2,60001,103,60001103,19,A,A,A,A,A,B,...,0,0,0,23812.596388,22983.493815,14663.337957,31246.723516,0.000000,1019,1
3,60001,104,60001104,19,A,A,A,A,A,C,...,0,0,0,17191.832515,22983.493815,11200.744542,18125.280372,0.000000,1019,1
4,60001,105,60001105,19,A,A,A,A,A,C,...,0,0,265,20261.485463,22983.493815,11200.744542,0.000000,0.000000,1019,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35422,80569,108,80569108,20,B,A,D,D,A,A,...,0,0,0,2812.010290,2449.173357,2449.173357,0.000000,0.000000,1056,2
35423,80570,101,80570101,20,A,A,A,A,A,A,...,0,1248,0,11481.496934,13076.665735,13076.665735,11648.039744,0.000000,1126,1
35424,80571,101,80571101,20,A,A,A,A,A,A,...,0,0,0,8357.376060,7085.589291,7085.589291,9920.807391,0.000000,1144,1
35425,80571,102,80571102,20,A,A,A,A,A,A,...,0,1230,0,8389.102961,7085.589291,7085.589291,9141.136948,0.000000,1144,1
35426,80571,103,80571103,20,A,A,A,A,A,A,...,0,0,0,7471.432983,7085.589291,7085.589291,0.000000,0.000000,1144,1

In [5]:
!whoami

jovyan