In [1]:
import pandas as pd
import cudf
import requests
import json

In [88]:
apple = pd.read_csv('data/applemobilitytrends-2020-06-29.csv')
google = pd.read_csv('data/Global_Mobility_Report.csv')
apple = apple[apple['country'] == 'Germany']
google = google[google['country_region_code'] == 'DE']
rki = pd.read_csv('data/RKI_COVID19.csv')

/opt/conda/envs/rapids/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [89]:
rki

,ObjectId,IdBundesland,Bundesland,Landkreis,Altersgruppe,Geschlecht,AnzahlFall,AnzahlTodesfall,Meldedatum,IdLandkreis,Datenstand,NeuerFall,NeuerTodesfall,Refdatum,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn,Altersgruppe2
0,15175481,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/14 00:00:00,1001,"02.07.2020, 00:00 Uhr",0,-9,2020/03/16 00:00:00,0,1,1,Nicht übermittelt
1,15175482,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/19 00:00:00,1001,"02.07.2020, 00:00 Uhr",0,-9,2020/03/13 00:00:00,0,1,1,Nicht übermittelt
2,15175483,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/19 00:00:00,1001,"02.07.2020, 00:00 Uhr",0,-9,2020/03/16 00:00:00,0,1,1,Nicht übermittelt
3,15175484,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/21 00:00:00,1001,"02.07.2020, 00:00 Uhr",0,-9,2020/03/13 00:00:00,0,1,1,Nicht übermittelt
4,15175485,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/27 00:00:00,1001,"02.07.2020, 00:00 Uhr",0,-9,2020/03/22 00:00:00,0,1,1,Nicht übermittelt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157093,15332574,16,Thüringen,LK Altenburger Land,A80+,M,1,0,2020/06/09 00:00:00,16077,"02.07.2020, 00:00 Uhr",0,-9,2020/05/19 00:00:00,0,1,1,Nicht übermittelt
157094,15332575,16,Thüringen,LK Altenburger Land,A80+,W,1,0,2020/05/06 00:00:00,16077,"02.07.2020, 00:00 Uhr",0,-9,2020/05/04 00:00:00,0,1,1,Nicht übermittelt
157095,15332576,16,Thüringen,LK Altenburger Land,A80+,W,1,0,2020/05/11 00:00:00,16077,"02.07.2020, 00:00 Uhr",0,-9,2020/05/01 00:00:00,0,1,1,Nicht übermittelt
157096,15332577,16,Thüringen,LK Altenburger Land,A80+,W,2,0,2020/05/28 00:00:00,16077,"02.07.2020, 00:00 Uhr",0,-9,2020/05/28 00:00:00,0,2,0,Nicht übermittelt
157097,15332578,16,Thüringen,LK Altenburger Land,A80+,W,1,0,2020/06/09 00:00:00,16077,"02.07.2020, 00:00 Uhr",0,-9,2020/06/09 00:00:00,0,1,0,Nicht übermittelt

In [93]:
rki['AnzahlFall'].value_counts()

 1      135797
 2       14693
 3        3524
 4        1277
 5         624
 6         338
 7         223
 8         156
 9          97
 10         75
 13         43
 12         41
 11         36
 14         28
-1          21
 15         16
 19         16
 16         15
 20         11
 18         11
 17          8
 22          8
 27          5
 21          5
 29          4
 23          3
 26          3
 38          2
 24          2
 37          2
 63          1
 58          1
 48          1
 47          1
 46          1
 39          1
 85          1
 35          1
 34          1
 31          1
 30          1
 28          1
 25          1
 162         1
Name: AnzahlFall, dtype: int64

In [70]:
google.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2278 entries, 40013 to 42290
Data columns (total 13 columns):
country_region_code                                   2278 non-null object
country_region                                        2278 non-null object
sub_region_1                                          2144 non-null object
sub_region_2                                          0 non-null object
iso_3166_2_code                                       2144 non-null object
census_fips_code                                      0 non-null float64
date                                                  2278 non-null object
retail_and_recreation_percent_change_from_baseline    2278 non-null float64
grocery_and_pharmacy_percent_change_from_baseline     2275 non-null float64
parks_percent_change_from_baseline                    2260 non-null float64
transit_stations_percent_change_from_baseline         2278 non-null float64
workplaces_percent_change_from_baseline               2278 non-null float64
residential_percent_change_from_baseline              2278 non-null float64
dtypes: float64(7), object(6)
memory usage: 249.2+ KB

In [71]:
google

,country_region_code,country_region,sub_region_1,sub_region_2,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
40013,DE,Germany,NaN,NaN,NaN,NaN,2020-02-15,6.0,1.0,45.0,10.0,0.0,-1.0
40014,DE,Germany,NaN,NaN,NaN,NaN,2020-02-16,7.0,10.0,9.0,6.0,-1.0,0.0
40015,DE,Germany,NaN,NaN,NaN,NaN,2020-02-17,2.0,2.0,7.0,1.0,-2.0,0.0
40016,DE,Germany,NaN,NaN,NaN,NaN,2020-02-18,2.0,2.0,10.0,1.0,-1.0,1.0
40017,DE,Germany,NaN,NaN,NaN,NaN,2020-02-19,3.0,0.0,6.0,-1.0,-1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42286,DE,Germany,Thuringia,NaN,DE-TH,NaN,2020-06-23,-7.0,-5.0,97.0,-5.0,-16.0,2.0
42287,DE,Germany,Thuringia,NaN,DE-TH,NaN,2020-06-24,-6.0,-3.0,104.0,-2.0,-15.0,2.0
42288,DE,Germany,Thuringia,NaN,DE-TH,NaN,2020-06-25,-9.0,-3.0,73.0,-7.0,-16.0,2.0
42289,DE,Germany,Thuringia,NaN,DE-TH,NaN,2020-06-26,-14.0,-5.0,109.0,-3.0,-16.0,1.0
42290,DE,Germany,Thuringia,NaN,DE-TH,NaN,2020-06-27,-24.0,-7.0,97.0,1.0,11.0,-2.0

In [41]:
 apple_gpu[apple_gpu['region'] == 'Germany']

,geo_type,region,transportation_type,alternative_name,sub-region,country,2020-01-13,2020-01-14,2020-01-15,2020-01-16,...,2020-06-20,2020-06-21,2020-06-22,2020-06-23,2020-06-24,2020-06-25,2020-06-26,2020-06-27,2020-06-28,2020-06-29
45,country/region,Germany,driving,Deutschland,None,None,100.0,101.31,102.82,104.61,...,123.26,127.78,121.89,127.65,128.77,131.70,145.55,128.61,129.62,127.65
46,country/region,Germany,transit,Deutschland,None,None,100.0,102.85,102.41,105.37,...,94.71,95.46,102.85,106.91,106.25,110.48,110.65,108.76,99.43,105.92
47,country/region,Germany,walking,Deutschland,None,None,100.0,104.04,107.18,110.76,...,131.78,112.89,115.69,123.12,122.28,122.41,132.81,135.19,101.98,115.93

In [60]:
response = requests.get("https://covidmap.umd.edu/api/region")
response = json.loads(response.text)
response = response['data']
[dictionary for dictionary in response if dictionary['country']=='Germany']

[{'country': 'Germany', 'region': 'Baden-Württemberg'},
 {'country': 'Germany', 'region': 'Bayern'},
 {'country': 'Germany', 'region': 'Berlin'},
 {'country': 'Germany', 'region': 'Brandenburg'},
 {'country': 'Germany', 'region': 'Bremen'},
 {'country': 'Germany', 'region': 'Hamburg'},
 {'country': 'Germany', 'region': 'Hessen'},
 {'country': 'Germany', 'region': 'Mecklenburg-Vorpommern'},
 {'country': 'Germany', 'region': 'Niedersachsen'},
 {'country': 'Germany', 'region': 'Nordrhein-Westfalen'},
 {'country': 'Germany', 'region': 'Rheinland-Pfalz'},
 {'country': 'Germany', 'region': 'Saarland'},
 {'country': 'Germany', 'region': 'Sachsen'},
 {'country': 'Germany', 'region': 'Sachsen-Anhalt'},
 {'country': 'Germany', 'region': 'Schleswig-Holstein'},
 {'country': 'Germany', 'region': 'Thüringen'}]

[{'country': 'Germany', 'region': 'Baden-Württemberg'},
 {'country': 'Germany', 'region': 'Bayern'},
 {'country': 'Germany', 'region': 'Berlin'},
 {'country': 'Germany', 'region': 'Brandenburg'},
 {'country': 'Germany', 'region': 'Bremen'},
 {'country': 'Germany', 'region': 'Hamburg'},
 {'country': 'Germany', 'region': 'Hessen'},
 {'country': 'Germany', 'region': 'Mecklenburg-Vorpommern'},
 {'country': 'Germany', 'region': 'Niedersachsen'},
 {'country': 'Germany', 'region': 'Nordrhein-Westfalen'},
 {'country': 'Germany', 'region': 'Rheinland-Pfalz'},
 {'country': 'Germany', 'region': 'Saarland'},
 {'country': 'Germany', 'region': 'Sachsen'},
 {'country': 'Germany', 'region': 'Sachsen-Anhalt'},
 {'country': 'Germany', 'region': 'Schleswig-Holstein'},
 {'country': 'Germany', 'region': 'Thüringen'}]

In [86]:
response = requests.get('https://covidmap.umd.edu/api/resources?indicator=flu&type=smoothed&country=Germany&region=all&daterange=20200114-20200726')
pd.DataFrame(json.loads(response.text)['data'])

,country,gid_0,gid_1,iso_code,region,sample_size,smoothed_ili,smoothed_ili_se,survey_date
0,Germany,DEU,DEU.1_1,DEU,Baden-Württemberg,305.0,0.000000,0.000000,20200501
1,Germany,DEU,DEU.1_1,DEU,Baden-Württemberg,531.0,0.004086,0.003623,20200502
2,Germany,DEU,DEU.1_1,DEU,Baden-Württemberg,946.0,0.004181,0.002708,20200503
3,Germany,DEU,DEU.1_1,DEU,Baden-Württemberg,1362.0,0.003654,0.002111,20200504
4,Germany,DEU,DEU.1_1,DEU,Baden-Württemberg,1777.0,0.003957,0.001932,20200505
...,...,...,...,...,...,...,...,...,...
901,Germany,DEU,DEU.16_1,DEU,Thüringen,1109.0,0.005025,0.002643,20200622
902,Germany,DEU,DEU.16_1,DEU,Thüringen,1121.0,0.005473,0.002713,20200623
903,Germany,DEU,DEU.16_1,DEU,Thüringen,1128.0,0.006493,0.002899,20200624
904,Germany,DEU,DEU.16_1,DEU,Thüringen,1134.0,0.007135,0.003076,20200625
905,Germany,DEU,DEU.16_1,DEU,Thüringen,1144.0,0.006063,0.002843,20200626

In [87]:
response = requests.get('https://covidmap.umd.edu/api/resources?indicator=flu&type=daily&country=Germany&region=all&daterange=20200114-20200726')
pd.DataFrame(json.loads(response.text)['data'])

,country,gid_0,gid_1,ili_se,ili_se_unw,iso_code,percent_ili,percent_ili_unw,region,sample_size,survey_date
0,Germany,DEU,DEU.1_1,0.000000,0.000000,DEU,0.000000,0.000000,Baden-Württemberg,283.0,20200501
1,Germany,DEU,DEU.1_1,0.008437,0.006230,DEU,0.009516,0.008850,Baden-Württemberg,226.0,20200502
2,Germany,DEU,DEU.1_1,0.004073,0.003400,DEU,0.004294,0.004819,Baden-Württemberg,415.0,20200503
3,Germany,DEU,DEU.1_1,0.003138,0.002401,DEU,0.002457,0.002404,Baden-Württemberg,416.0,20200504
4,Germany,DEU,DEU.1_1,0.004556,0.004159,DEU,0.004989,0.007229,Baden-Württemberg,415.0,20200505
...,...,...,...,...,...,...,...,...,...,...,...
843,Germany,DEU,DEU.16_1,0.000000,0.000000,DEU,0.000000,0.000000,Thüringen,162.0,20200622
844,Germany,DEU,DEU.16_1,0.006177,0.006116,DEU,0.004164,0.006135,Thüringen,163.0,20200623
845,Germany,DEU,DEU.16_1,0.009267,0.006390,DEU,0.009957,0.006410,Thüringen,156.0,20200624
846,Germany,DEU,DEU.16_1,0.010297,0.006154,DEU,0.009631,0.006173,Thüringen,162.0,20200625
847,Germany,DEU,DEU.16_1,0.011036,0.008519,DEU,0.012837,0.012121,Thüringen,165.0,20200626