In [1]:
import pandas as pd
import cudf
import requests
import json

In [2]:
apple = pd.read_csv('data/applemobilitytrends-2020-06-29.csv')
google = pd.read_csv('data/Global_Mobility_Report.csv')
apple = apple[apple['country'] == 'Germany']
google = google[google['country_region_code'] == 'DE']
rki = pd.read_csv('data/RKI_COVID19.csv')

/usr/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
rki

,ObjectId,IdBundesland,Bundesland,Landkreis,Altersgruppe,Geschlecht,AnzahlFall,AnzahlTodesfall,Meldedatum,IdLandkreis,Datenstand,NeuerFall,NeuerTodesfall,Refdatum,NeuGenesen,AnzahlGenesen,IstErkrankungsbeginn,Altersgruppe2
0,15175481,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/14 00:00:00,1001,"02.07.2020, 00:00 Uhr",0,-9,2020/03/16 00:00:00,0,1,1,Nicht übermittelt
1,15175482,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/19 00:00:00,1001,"02.07.2020, 00:00 Uhr",0,-9,2020/03/13 00:00:00,0,1,1,Nicht übermittelt
2,15175483,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/19 00:00:00,1001,"02.07.2020, 00:00 Uhr",0,-9,2020/03/16 00:00:00,0,1,1,Nicht übermittelt
3,15175484,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/21 00:00:00,1001,"02.07.2020, 00:00 Uhr",0,-9,2020/03/13 00:00:00,0,1,1,Nicht übermittelt
4,15175485,1,Schleswig-Holstein,SK Flensburg,A15-A34,M,1,0,2020/03/27 00:00:00,1001,"02.07.2020, 00:00 Uhr",0,-9,2020/03/22 00:00:00,0,1,1,Nicht übermittelt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157093,15332574,16,Thüringen,LK Altenburger Land,A80+,M,1,0,2020/06/09 00:00:00,16077,"02.07.2020, 00:00 Uhr",0,-9,2020/05/19 00:00:00,0,1,1,Nicht übermittelt
157094,15332575,16,Thüringen,LK Altenburger Land,A80+,W,1,0,2020/05/06 00:00:00,16077,"02.07.2020, 00:00 Uhr",0,-9,2020/05/04 00:00:00,0,1,1,Nicht übermittelt
157095,15332576,16,Thüringen,LK Altenburger Land,A80+,W,1,0,2020/05/11 00:00:00,16077,"02.07.2020, 00:00 Uhr",0,-9,2020/05/01 00:00:00,0,1,1,Nicht übermittelt
157096,15332577,16,Thüringen,LK Altenburger Land,A80+,W,2,0,2020/05/28 00:00:00,16077,"02.07.2020, 00:00 Uhr",0,-9,2020/05/28 00:00:00,0,2,0,Nicht übermittelt
157097,15332578,16,Thüringen,LK Altenburger Land,A80+,W,1,0,2020/06/09 00:00:00,16077,"02.07.2020, 00:00 Uhr",0,-9,2020/06/09 00:00:00,0,1,0,Nicht übermittelt

In [4]:
rki['AnzahlFall'].value_counts()

 1      135797
 2       14693
 3        3524
 4        1277
 5         624
 6         338
 7         223
 8         156
 9          97
 10         75
 13         43
 12         41
 11         36
 14         28
-1          21
 15         16
 19         16
 16         15
 20         11
 18         11
 17          8
 22          8
 27          5
 21          5
 29          4
 23          3
 26          3
 38          2
 24          2
 37          2
 63          1
 58          1
 48          1
 47          1
 46          1
 39          1
 85          1
 35          1
 34          1
 31          1
 30          1
 28          1
 25          1
 162         1
Name: AnzahlFall, dtype: int64

In [5]:
google.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2278 entries, 40013 to 42290
Data columns (total 13 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   country_region_code                                 2278 non-null   object
 1   country_region                                      2278 non-null   object
 2   sub_region_1                                        2144 non-null   object
 3   sub_region_2                                        0 non-null      object
 4   iso_3166_2_code                                     2144 non-null   object
 5   census_fips_code                                    0 non-null      float64
 6   date                                                2278 non-null   object
 7   retail_and_recreation_percent_change_from_baseline  2278 non-null   float64
 8   grocery_and_pharmacy_percent_change_from_baseline   2275 non-null   float64
 9   parks_percent_change_from_baseline                  2260 non-null   float64
 10  transit_stations_percent_change_from_baseline       2278 non-null   float64
 11  workplaces_percent_change_from_baseline             2278 non-null   float64
 12  residential_percent_change_from_baseline            2278 non-null   float64
dtypes: float64(7), object(6)
memory usage: 249.2+ KB

In [6]:
google

,country_region_code,country_region,sub_region_1,sub_region_2,iso_3166_2_code,census_fips_code,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
40013,DE,Germany,NaN,NaN,NaN,NaN,2020-02-15,6.0,1.0,45.0,10.0,0.0,-1.0
40014,DE,Germany,NaN,NaN,NaN,NaN,2020-02-16,7.0,10.0,9.0,6.0,-1.0,0.0
40015,DE,Germany,NaN,NaN,NaN,NaN,2020-02-17,2.0,2.0,7.0,1.0,-2.0,0.0
40016,DE,Germany,NaN,NaN,NaN,NaN,2020-02-18,2.0,2.0,10.0,1.0,-1.0,1.0
40017,DE,Germany,NaN,NaN,NaN,NaN,2020-02-19,3.0,0.0,6.0,-1.0,-1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
42286,DE,Germany,Thuringia,NaN,DE-TH,NaN,2020-06-23,-7.0,-5.0,97.0,-5.0,-16.0,2.0
42287,DE,Germany,Thuringia,NaN,DE-TH,NaN,2020-06-24,-6.0,-3.0,104.0,-2.0,-15.0,2.0
42288,DE,Germany,Thuringia,NaN,DE-TH,NaN,2020-06-25,-9.0,-3.0,73.0,-7.0,-16.0,2.0
42289,DE,Germany,Thuringia,NaN,DE-TH,NaN,2020-06-26,-14.0,-5.0,109.0,-3.0,-16.0,1.0
42290,DE,Germany,Thuringia,NaN,DE-TH,NaN,2020-06-27,-24.0,-7.0,97.0,1.0,11.0,-2.0

In [7]:
 apple_gpu[apple_gpu['region'] == 'Germany']

NameError: name 'apple_gpu' is not defined

In [7]:
response = requests.get("https://covidmap.umd.edu/api/region")
response = json.loads(response.text)
response = response['data']
[dictionary for dictionary in response if dictionary['country']=='Germany']

[{'country': 'Germany', 'region': 'Baden-Württemberg'},
 {'country': 'Germany', 'region': 'Bayern'},
 {'country': 'Germany', 'region': 'Berlin'},
 {'country': 'Germany', 'region': 'Brandenburg'},
 {'country': 'Germany', 'region': 'Bremen'},
 {'country': 'Germany', 'region': 'Hamburg'},
 {'country': 'Germany', 'region': 'Hessen'},
 {'country': 'Germany', 'region': 'Mecklenburg-Vorpommern'},
 {'country': 'Germany', 'region': 'Niedersachsen'},
 {'country': 'Germany', 'region': 'Nordrhein-Westfalen'},
 {'country': 'Germany', 'region': 'Rheinland-Pfalz'},
 {'country': 'Germany', 'region': 'Saarland'},
 {'country': 'Germany', 'region': 'Sachsen'},
 {'country': 'Germany', 'region': 'Sachsen-Anhalt'},
 {'country': 'Germany', 'region': 'Schleswig-Holstein'},
 {'country': 'Germany', 'region': 'Thüringen'}]

In [8]:
response = requests.get('https://covidmap.umd.edu/api/resources?indicator=flu&type=smoothed&country=Germany&region=all&daterange=20200114-20200726')
pd.DataFrame(json.loads(response.text)['data'])

,country,gid_0,gid_1,iso_code,region,sample_size,smoothed_ili,smoothed_ili_se,survey_date
0,Germany,DEU,DEU.1_1,DEU,Baden-Württemberg,305.0,0.000000,0.000000,20200501
1,Germany,DEU,DEU.1_1,DEU,Baden-Württemberg,531.0,0.004086,0.003623,20200502
2,Germany,DEU,DEU.1_1,DEU,Baden-Württemberg,946.0,0.004181,0.002708,20200503
3,Germany,DEU,DEU.1_1,DEU,Baden-Württemberg,1362.0,0.003654,0.002111,20200504
4,Germany,DEU,DEU.1_1,DEU,Baden-Württemberg,1777.0,0.003957,0.001932,20200505
...,...,...,...,...,...,...,...,...,...
1013,Germany,DEU,DEU.16_1,DEU,Thüringen,788.0,0.007454,0.003805,20200629
1014,Germany,DEU,DEU.16_1,DEU,Thüringen,1052.0,0.006618,0.003173,20200630
1015,Germany,DEU,DEU.16_1,DEU,Thüringen,1021.0,0.006235,0.003159,20200701
1016,Germany,DEU,DEU.16_1,DEU,Thüringen,993.0,0.005610,0.002993,20200702
1017,Germany,DEU,DEU.16_1,DEU,Thüringen,934.0,0.003659,0.002490,20200703

In [9]:
response = requests.get('https://covidmap.umd.edu/api/resources?indicator=flu&type=daily&country=Germany&region=all&daterange=20200114-20200726')
pd.DataFrame(json.loads(response.text)['data'])

,country,gid_0,gid_1,ili_se,ili_se_unw,iso_code,percent_ili,percent_ili_unw,region,sample_size,survey_date
0,Germany,DEU,DEU.1_1,0.000000,0.000000,DEU,0.000000,0.000000,Baden-Württemberg,283.0,20200501
1,Germany,DEU,DEU.1_1,0.008437,0.006230,DEU,0.009516,0.008850,Baden-Württemberg,226.0,20200502
2,Germany,DEU,DEU.1_1,0.004073,0.003400,DEU,0.004294,0.004819,Baden-Württemberg,415.0,20200503
3,Germany,DEU,DEU.1_1,0.003138,0.002401,DEU,0.002457,0.002404,Baden-Württemberg,416.0,20200504
4,Germany,DEU,DEU.1_1,0.004556,0.004159,DEU,0.004989,0.007229,Baden-Württemberg,415.0,20200505
...,...,...,...,...,...,...,...,...,...,...,...
941,Germany,DEU,DEU.16_1,0.000000,0.000000,DEU,0.000000,0.000000,Thüringen,142.0,20200629
942,Germany,DEU,DEU.16_1,0.000000,0.000000,DEU,0.000000,0.000000,Thüringen,127.0,20200630
943,Germany,DEU,DEU.16_1,0.010038,0.011223,DEU,0.008385,0.016000,Thüringen,125.0,20200701
944,Germany,DEU,DEU.16_1,0.007611,0.007435,DEU,0.005341,0.007463,Thüringen,134.0,20200702
945,Germany,DEU,DEU.16_1,0.000000,0.000000,DEU,0.000000,0.000000,Thüringen,106.0,20200703

In [10]:
 migra = pd.read_csv('data/migration_integration_regionen_daten.csv')
 migra

,RS,NAME,INSGESAMT,INSG_M,INSG_W,AUSL_INSG,AUSL_M,AUSL_W,IIU6,IMU6,...,ANT_SCH_OFF,ANT_SCH_ANERK,ANT_SCH_ABGEL,ANT_SCH_SYRIEN,ANT_SCH_AFGHANISTAN,ANT_SCH_IRAK,ANT_SCH_RUSSLAND,ANT_SCH_IRAN,ANT_SCH_KOSOVO,SCH_VERAENDERUNG
0,1001,"Flensburg, Stadt",89504,44599,44905,12702,7148,5554,4961,2518,...,11.4,79.8,8.8,44.3,13.4,15.5,1.6,3.9,1.1,23.1
1,1002,"Kiel, Stadt",247548,120566,126982,28564,14768,13796,13408,6804,...,11.6,81.1,7.3,42.0,8.1,18.3,5.3,3.3,0.6,8.9
2,1003,"Lübeck, Stadt",217198,104371,112827,21984,11396,10588,11257,5863,...,14.8,74.6,10.6,31.8,12.8,12.5,6.7,6.8,0.8,10.2
3,1004,"Neumünster, Stadt",79487,39241,40246,9216,5121,4095,4202,2194,...,38.3,42.3,19.2,27.9,18.6,9.9,4.0,6.1,1.9,20.0
4,1051,Dithmarschen,133210,65720,67490,7597,4161,3436,6465,3267,...,17.4,71.5,11.1,37.0,17.6,7.2,3.5,4.3,1.5,-0.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,16073,Saalfeld-Rudolstadt,106356,52388,53968,2952,1719,1233,4970,2581,...,21.5,68.2,10.3,33.0,21.9,12.4,1.3,0.4,3.0,-5.3
397,16074,Saale-Holzland-Kreis,83051,41360,41691,2645,1633,1012,4272,2172,...,20.0,77.1,2.9,28.6,25.7,11.4,NaN,NaN,NaN,0.0
398,16075,Saale-Orla-Kreis,80868,40119,40749,2732,1628,1104,3986,2027,...,24.5,66.0,10.1,35.6,21.8,16.0,5.9,0.5,1.6,-8.3
399,16076,Greiz,98159,48326,49833,2260,1330,930,4505,2317,...,27.6,55.2,17.2,35.8,17.2,14.9,4.5,0.7,0.7,1.5
400,16077,Altenburger Land,90118,44138,45980,3138,1875,1263,4003,2035,...,13.0,79.5,7.5,41.8,25.5,13.4,4.6,NaN,0.8,-4.0

In [11]:
krim = pd.read_csv("data/kriminalstatistik_kreise.csv", decimal=",")
krim["kreis"] = krim["Stadt-/Landkreis"] + " " + krim["Kreisart"]
krim = krim.loc[krim['Straftat'] == "Straftaten insgesamt"]
krim = krim.iloc[:, 5:19]
krim

,erfasste Fälle,HZ nach Zensus,Anzahl,in %,gedroht,geschossen,Fälle,Aufklärungsquote,Tat-verdächtige insgesamt,männlich,weiblich,Nichtdeutsche Tatverdächtige,in Prozent,kreis
0,8.907,10.187,841.000,9.4,11,5,5.177,58.1,3.493,2.716,777.000,1.182,33.8,Flensburg KfS
1,23.934,9.673,1.958,8.2,27,13,11.493,48.0,7.949,6.099,1.850,2.194,27.6,Kiel KfS
2,23.614,10.896,1.829,7.7,23,15,12.964,54.9,8.405,6.336,2.069,1.958,23.3,Lübeck KfS
3,9.751,12.238,681.000,7.0,13,8,6.325,64.9,5.026,3.560,1.466,2.496,49.7,Neumünster KfS
4,7.262,5.437,515.000,7.1,9,6,4.034,55.5,3.024,2.230,794.000,445.000,14.7,Dithmarschen K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,5.793,5.348,395.000,6.8,6,20,3.968,68.5,2.508,1.896,612.000,284.000,11.3,Saalfeld-Rudolstadt LK
397,4.373,5.174,309.000,7.1,2,13,3.051,69.8,2.136,1.656,480.000,282.000,13.2,Saale-Holzland-Kreis LK
398,4.747,5.764,309.000,6.5,1,8,3.045,64.1,2.157,1.663,494.000,232.000,10.8,Saale-Orla-Kreis LK
399,4.483,4.496,336.000,7.5,2,4,3.044,67.9,1.926,1.502,424.000,250.000,13.0,Greiz LK
400,5.574,6.085,483.000,8.7,1,5,3.617,64.9,2.266,1.672,594.000,299.000,13.2,Altenburger Land LK

In [12]:
lookup = pd.read_csv("data/join_kreise.csv")
agg = rki.groupby(['Landkreis', "Bundesland"]).sum()
joined = lookup.merge(agg, left_on='pk_rki', right_on='Landkreis').merge(krim, left_on="pk_krim", right_on="kreis").merge(migra, left_on="pk_migra", right_on="NAME")
joined

,pk_migra,pk_rki,pk_krim,ObjectId,IdBundesland,AnzahlFall,AnzahlTodesfall,IdLandkreis,NeuerFall,NeuerTodesfall,...,ANT_SCH_OFF,ANT_SCH_ANERK,ANT_SCH_ABGEL,ANT_SCH_SYRIEN,ANT_SCH_AFGHANISTAN,ANT_SCH_IRAK,ANT_SCH_RUSSLAND,ANT_SCH_IRAN,ANT_SCH_KOSOVO,SCH_VERAENDERUNG
0,Ahrweiler,LK Ahrweiler,Ahrweiler LK,2697020862,1239,201,1,1262187,4,-1584,...,8.1,86.4,5.5,58.2,8.1,2.1,1.0,3.8,3.6,5.0
1,Aichach-Friedberg,LK Aichach-Friedberg,Aichach-Friedberg LK,4423783979,2601,390,20,2823819,1,-2457,...,19.0,67.9,13.1,29.1,13.4,6.7,1.9,1.1,2.6,14.5
2,Alb-Donau-Kreis,LK Alb-Donau-Kreis,Alb-Donau-Kreis LK,8734433422,4576,658,27,4819100,3,-4941,...,24.0,64.7,11.3,32.2,11.3,8.9,0.8,1.9,7.8,1.8
3,Altenburger Land,LK Altenburger Land,Altenburger Land LK,1134608071,1184,76,4,1189698,0,-630,...,13.0,79.5,7.5,41.8,25.5,13.4,4.6,NaN,0.8,-4.0
4,Altenkirchen (Westerwald),LK Altenkirchen,Altenkirchen (Westerwald) LK,2407536613,1106,172,11,1126856,0,-1332,...,12.6,74.4,13.3,42.1,16.0,2.1,2.1,7.3,3.7,6.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,"Wolfsburg, Stadt",SK Wolfsburg,Wolfsburg KfS,4311650938,852,370,51,881252,0,-2205,...,14.6,76.8,8.4,36.3,8.4,12.4,1.7,3.0,4.1,11.1
408,"Worms, Stadt",SK Worms,Worms KfS,3276859075,1505,224,7,1573585,0,-1872,...,9.0,83.8,7.1,43.2,11.2,1.2,3.8,3.6,1.0,9.1
409,"Wuppertal, Stadt",SK Wuppertal,Wuppertal KfS,12478733672,4105,1016,86,4206804,2,-6804,...,6.1,83.8,10.0,38.5,3.4,7.9,3.7,1.7,3.3,7.3
410,"Würzburg, Stadt",SK Würzburg,Würzburg KfS,6427609650,3780,489,52,4058460,1,-3330,...,2.2,94.0,3.7,33.3,11.7,2.3,8.9,2.6,1.7,16.5
411,"Zweibrücken, Stadt",SK Zweibrücken,Zweibrücken KfS,670618718,308,44,1,322080,0,-387,...,7.5,86.7,5.8,60.1,10.4,1.2,1.2,1.7,4.0,13.8